/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import static principal.MenuPrincipalAd.escritorio;
import static ventas.CajaAd.buscar;
import static ventas.CajaAd.cambio;
import static ventas.CajaAd.recibi;
import static ventas.CajaAd.tablaCaja;
import static ventas.CajaAd.total;

/**
 *
 * @author 
 */
public class RegistroVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Usuarios
     */
    public RegistroVentas() {
        initComponents();
        tablaVentas.getTableHeader().setDefaultRenderer(new principal.EstiloTablaHeader());
        tablaVentas.setDefaultRenderer(Object.class, new principal.EstiloTablaRenderer());
        this.setFrameIcon(new ImageIcon("C:\\Pos\\data\\imagenes\\caja\\icono1.png"));
        tablaVentas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        limpiaCampos();
    }

    void limpiaCampos() {
        if (tablaVentas.getSelectedRow() > -1) {
            tablaVentas.removeRowSelectionInterval(tablaVentas.getSelectedRow(), tablaVentas.getSelectedRow());
        }
        fecha.setDate(null);
        buscar.setText("");
        OpcionesVen.listar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        buscar = new app.bolivia.swing.JCTextField();
        codigoL1 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        eliminar = new javax.swing.JButton();
        verDetalle = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        buscF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ventasH = new javax.swing.JButton();
        ImprimirVentas1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("REGISTRO VENTAS");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. VENTA", "TOTAL", "FECHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tablaVentas);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscar.setBackground(new java.awt.Color(34, 102, 145));
        buscar.setBorder(null);
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar.setOpaque(false);
        buscar.setPhColor(new java.awt.Color(255, 255, 255));
        buscar.setPlaceholder("No. VENTA");
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarKeyTyped(evt);
            }
        });
        jPanel4.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, -1));

        codigoL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoL1.setIcon(new javax.swing.ImageIcon("C:\\Pos\\data\\imagenes\\usuarios\\buscarL.png")); // NOI18N
        jPanel4.add(codigoL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 250, 52));

        fecha.setDateFormatString("dd/MM/yyyy");
        fecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, 30));

        eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eliminar.setText("Ver Detalle");
        eliminar.setBorder(null);
        eliminar.setBorderPainted(false);
        eliminar.setContentAreaFilled(false);
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel4.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        verDetalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        verDetalle.setIcon(new javax.swing.ImageIcon("C:\\Pos\\data\\imagenes\\principal\\informacion1.png")); // NOI18N
        verDetalle.setText("Ver detalle");
        verDetalle.setBorder(null);
        verDetalle.setBorderPainted(false);
        verDetalle.setContentAreaFilled(false);
        verDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verDetalle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verDetalle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDetalleActionPerformed(evt);
            }
        });
        jPanel4.add(verDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, 120));

        limpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        limpiar.setIcon(new javax.swing.ImageIcon("C:\\Pos\\data\\imagenes\\usuarios\\limpiar1.png")); // NOI18N
        limpiar.setText("Limpiar Campos");
        limpiar.setBorder(null);
        limpiar.setBorderPainted(false);
        limpiar.setContentAreaFilled(false);
        limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        limpiar.setRolloverIcon(new javax.swing.ImageIcon("C:\\Pos\\data\\imagenes\\usuarios\\limpiar2.png")); // NOI18N
        limpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel4.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        buscF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buscF.setIcon(new javax.swing.ImageIcon("C:\\Pos\\data\\imagenes\\caja\\buscaF1.png")); // NOI18N
        buscF.setToolTipText("Buscar");
        buscF.setBorder(null);
        buscF.setBorderPainted(false);
        buscF.setContentAreaFilled(false);
        buscF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscF.setRolloverIcon(new javax.swing.ImageIcon("C:\\Pos\\data\\imagenes\\caja\\buscaF2.png")); // NOI18N
        buscF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscFActionPerformed(evt);
            }
        });
        jPanel4.add(buscF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Fecha");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        ventasH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ventasH.setIcon(new javax.swing.ImageIcon("C:\\Pos\\data\\imagenes\\caja\\ventasH1.png")); // NOI18N
        ventasH.setToolTipText("Buscar");
        ventasH.setBorder(null);
        ventasH.setBorderPainted(false);
        ventasH.setContentAreaFilled(false);
        ventasH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ventasH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ventasH.setRolloverIcon(new javax.swing.ImageIcon("C:\\Pos\\data\\imagenes\\caja\\ventasH2.png")); // NOI18N
        ventasH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ventasH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasHActionPerformed(evt);
            }
        });
        jPanel4.add(ventasH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        ImprimirVentas1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ImprimirVentas1.setIcon(new javax.swing.ImageIcon("C:\\Pos\\data\\imagenes\\principal\\ventas2.png")); // NOI18N
        ImprimirVentas1.setText("Imprimir");
        ImprimirVentas1.setBorder(null);
        ImprimirVentas1.setBorderPainted(false);
        ImprimirVentas1.setContentAreaFilled(false);
        ImprimirVentas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImprimirVentas1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ImprimirVentas1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ImprimirVentas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirVentas1ActionPerformed(evt);
            }
        });
        jPanel4.add(ImprimirVentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, 120));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiaCampos();
    }//GEN-LAST:event_limpiarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
            
       if (tablaVentas.getRowCount() > 0) {
           if (tablaVentas.getSelectedRowCount() > 0) {
                int fila = tablaVentas.getSelectedRow();
                String idFact = tablaVentas.getValueAt(fila, 0).toString();
                
                System.out.println("el id de la venta es  "+idFact);
                
                CajaDetalle cajadetalle = new CajaDetalle();
                
                escritorio.add(cajadetalle).setLocation(0, 3);
                cajadetalle.calcular();
                cajadetalle.show();
                DecimalFormat formatea;
                formatea = new DecimalFormat("###,###.##");
                String verListaDetalle = OpcionesVen.listarDetalle(idFact);
                String total=tablaVentas.getValueAt(fila, 1).toString();
                cajadetalle.totalDetalle.setText(formatea.format(Math.rint(Integer.parseInt(total)* 100) / 100));
                cajadetalle.numFacDetalle.setText(idFact);
                cajadetalle.fechaDetalle.setText(tablaVentas.getValueAt(fila, 2).toString());
                
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un registro.", "Registro Ventas", 0,
                        new ImageIcon("C:\\Pos\\data\\imagenes\\usuarios\\info.png"));
            }

        } else {
            JOptionPane.showMessageDialog(this, "No hay registros\npara ver.", "Registro Ventas", 0,
                    new ImageIcon("C:\\Pos\\data\\imagenes\\usuarios\\info.png"));
        }
      
    }//GEN-LAST:event_eliminarActionPerformed

    private void verDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDetalleActionPerformed
             
       if (tablaVentas.getRowCount() > 0) {
           if (tablaVentas.getSelectedRowCount() > 0) {
                int fila = tablaVentas.getSelectedRow();
                String idFact = tablaVentas.getValueAt(fila, 0).toString();
                System.out.println("el id de la venta es  "+idFact);
                CajaDetalle cajadetalle = new CajaDetalle();
                escritorio.add(cajadetalle).setLocation(0, 3);
                cajadetalle.calcular();
                cajadetalle.show();
                DecimalFormat formatea;
                formatea = new DecimalFormat("###,###.##");
                String verListaDetalle = OpcionesVen.listarDetalle(idFact);
                String total=tablaVentas.getValueAt(fila, 1).toString();
                cajadetalle.totalDetalle.setText(formatea.format(Math.rint(Integer.parseInt(total)* 100) / 100));
                cajadetalle.numFacDetalle.setText(idFact);
                cajadetalle.fechaDetalle.setText(tablaVentas.getValueAt(fila, 2).toString());
                
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un registro.", "Registro Ventas", 0,
                        new ImageIcon("C:\\Pos\\data\\imagenes\\usuarios\\info.png"));
            }

        } else {
            JOptionPane.showMessageDialog(this, "No hay registros\npara ver.", "Registro Ventas", 0,
                    new ImageIcon("C:\\Pos\\data\\imagenes\\usuarios\\info.png"));
        }
        
       
    }//GEN-LAST:event_verDetalleActionPerformed

    private void buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyTyped
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_buscarKeyTyped

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
       
    }//GEN-LAST:event_buscarKeyReleased

    private void buscFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscFActionPerformed
        if (fecha.getDate() == null) {
            OpcionesVen.listar("");
        } else {
            String formato = fecha.getDateFormatString();
            Date date = fecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            System.out.println("String.valueOf(sdf.format(date))"+String.valueOf(sdf.format(date)));
           String total=OpcionesVen.listar(String.valueOf(sdf.format(date)));
           
        fecha.setDate(null);
               ImpresoraZ impresora= new ImpresoraZ();
               
                
                impresora.imprimirTicket(total,String.valueOf(sdf.format(date)));
           
        }
    }//GEN-LAST:event_buscFActionPerformed

    private void ventasHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasHActionPerformed
        Date sistemaFech = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String fecH = formato.format(sistemaFech);
        OpcionesVen.listar(fecH);
        fecha.setDate(null);
        
    }//GEN-LAST:event_ventasHActionPerformed

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        fecha.setDate(null);
        OpcionesVen.listar("");
    }//GEN-LAST:event_buscarMouseClicked

    private void buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            OpcionesVen.listar(buscar.getText());
        }
         
         
    }//GEN-LAST:event_buscarKeyPressed

    private void ImprimirVentas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirVentas1ActionPerformed
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(null, "¿Desea realizar cierre?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            
            Date sistemaFech = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
             System.out.println("sistemaFech"+sistemaFech);
        String fecH = formato.format(sistemaFech);
       String total = OpcionesVen.listar(fecH);
        fecha.setDate(null);
               ImpresoraZ impresora= new ImpresoraZ();
               impresora.imprimirTicket(total,"");
                }else {
          }
    }//GEN-LAST:event_ImprimirVentas1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImprimirVentas1;
    private javax.swing.JButton buscF;
    private app.bolivia.swing.JCTextField buscar;
    private javax.swing.JLabel codigoL1;
    private javax.swing.JButton eliminar;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    public static javax.swing.JTable tablaVentas;
    private javax.swing.JButton ventasH;
    private javax.swing.JButton verDetalle;
    // End of variables declaration//GEN-END:variables
}
